# Generated by Django 4.2.9 on 2024-02-20 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата редактирования')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитан?')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by_user', to='blogs.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_posts_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прочтенный пост',
                'verbose_name_plural': 'Прочтенные посты',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
