# Generated by Django 4.2.9 on 2024-02-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_readpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readpost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_by_user', to='blogs.post', verbose_name='Пост'),
        ),
    ]
