# Generated by Django 4.2.9 on 2024-02-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_readpost'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='read_posts',
            field=models.ManyToManyField(blank=True, related_name='read_by', to='blogs.post'),
        ),
    ]
