# Generated by Django 4.2.9 on 2024-02-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_read_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='read_posts',
        ),
    ]
