# Generated by Django 4.2.9 on 2024-02-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_readpost_post'),
        ('accounts', '0003_remove_account_read_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='read_posts',
            field=models.ManyToManyField(blank=True, related_name='read_by', to='blogs.post'),
        ),
    ]
